### ISSUE TITLE
Laravel Sail DevContainer

### ISSUE THREAD

**Issue by mikebronner** [videlalvaro/test-app#1]
Hi @videlalvaro, thanks for getting this into Laravel Sail.

I just updated Sail and tried to get things to work, but the CodeSpaces devcontainer always fails to build. I was wondering if I could get your insight on what might be wrong. I'm pretty sure it's a configuration issue.

`.devcontainer/devcontainer.json`:

```json
// https://aka.ms/devcontainer.json
{
	"name": "Existing Docker Compose (Extend)",
	"dockerComposeFile": [
		"../docker-compose.yml"
	],
	"service": "laravel.test",
	"workspaceFolder": "/var/www/html",
	"settings": {},
	"extensions": [
		// "mikestead.dotenv",
		// "amiralizadeh9480.laravel-extra-intellisense",
		// "ryannaddy.laravel-artisan",
		// "onecentlin.laravel5-snippets",
		// "onecentlin.laravel-blade"
	],
	"remoteUser": "sail",
	// "forwardPorts": [],
	// "runServices": [],
	// "postCreateCommand": "apt-get update && apt-get install -y curl",
	// "shutdownAction": "none",
}
```

`docker-composer.yml`:

```yml
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '1000'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis
    pgsql:
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: 'totality'
            POSTGRES_USER: 'forge'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sailpgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "totality", "-U", "forge"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:
        driver: local
    sailredis:
        driver: local
```

And finally the creation log:
```
Configuration starting...
2021-08-22T17:46:03: [2021-08-22T17:46:04.588Z] @microsoft/vscode-dev-containers-cli 0.42.0.
[2021-08-22T17:46:04.588Z] Start: Resolving Remote
[2021-08-22T17:46:04.744Z] Start: Run: docker ps -q -a --filter label=Type=codespaces
[2021-08-22T17:46:04.773Z] Stop (29 ms): Run: docker ps -q -a --filter label=Type=codespaces
[2021-08-22T17:46:04.774Z] Start: Run: docker inspect --type container 8ff6fe1b0582
[2021-08-22T17:46:04.836Z] Stop (62 ms): Run: docker inspect --type container 8ff6fe1b0582
[2021-08-22T17:46:04.837Z] Start: Starting container
[2021-08-22T17:46:04.837Z] Start: Run: docker start 8ff6fe1b058212f14aed4a8ae9eb9cd60be2cefe41f783396ffea115e84e3853
[2021-08-22T17:46:07.964Z] Stop (3127 ms): Run: docker start 8ff6fe1b058212f14aed4a8ae9eb9cd60be2cefe41f783396ffea115e84e3853
[2021-08-22T17:46:07.964Z] Stop (3127 ms): Starting container
[2021-08-22T17:46:07.964Z] Start: Run: docker ps -q -a --filter label=Type=codespaces
[2021-08-22T17:46:07.994Z] Stop (30 ms): Run: docker ps -q -a --filter label=Type=codespaces
[2021-08-22T17:46:07.994Z] Start: Run: docker inspect --type container 8ff6fe1b0582
[2021-08-22T17:46:08.022Z] Stop (28 ms): Run: docker inspect --type container 8ff6fe1b0582
[2021-08-22T17:46:08.023Z] Start: Inspecting container
[2021-08-22T17:46:08.023Z] Start: Run: docker inspect --type container 8ff6fe1b058212f14aed4a8ae9eb9cd60be2cefe41f783396ffea115e84e3853
[2021-08-22T17:46:08.052Z] Stop (29 ms): Run: docker inspect --type container 8ff6fe1b058212f14aed4a8ae9eb9cd60be2cefe41f783396ffea115e84e3853
[2021-08-22T17:46:08.052Z] Stop (29 ms): Inspecting container
[2021-08-22T17:46:08.053Z] Start: Run in container: /bin/sh
[2021-08-22T17:46:08.056Z] Start: Run in container: uname -m
[2021-08-22T17:46:08.162Z] x86_64
[2021-08-22T17:46:08.162Z] 
[2021-08-22T17:46:08.162Z] Stop (106 ms): Run in container: uname -m
[2021-08-22T17:46:08.163Z] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2021-08-22T17:46:08.166Z] NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.5
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
[2021-08-22T17:46:08.166Z] 
[2021-08-22T17:46:08.166Z] Stop (3 ms): Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2021-08-22T17:46:08.167Z] Start: Run in container: cat /etc/passwd
[2021-08-22T17:46:08.169Z] Stop (2 ms): Run in container: cat /etc/passwd
[2021-08-22T17:46:08.171Z] Start: Run in container: test -d /root/.vscode-remote
[2021-08-22T17:46:08.173Z] 
[2021-08-22T17:46:08.173Z] 
[2021-08-22T17:46:08.173Z] Stop (2 ms): Run in container: test -d /root/.vscode-remote
[2021-08-22T17:46:08.174Z] Start: Run in container: test -f /var/vscode-remote/.patchEtcEnvironmentMarker
[2021-08-22T17:46:08.178Z] 
[2021-08-22T17:46:08.178Z] 
[2021-08-22T17:46:08.178Z] Stop (4 ms): Run in container: test -f /var/vscode-remote/.patchEtcEnvironmentMarker
[2021-08-22T17:46:08.178Z] Start: Run in container: test -f /var/vscode-remote/.patchEtcProfileMarker
[2021-08-22T17:46:08.179Z] 
[2021-08-22T17:46:08.179Z] 
[2021-08-22T17:46:08.179Z] Stop (1 ms): Run in container: test -f /var/vscode-remote/.patchEtcProfileMarker
[2021-08-22T17:46:08.179Z] Start: Run in container: test ! -f '/root/.vscode-remote/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.183Z] 
[2021-08-22T17:46:08.183Z] 
[2021-08-22T17:46:08.183Z] Exit code 1
[2021-08-22T17:46:08.183Z] Stop (4 ms): Run in container: test ! -f '/root/.vscode-remote/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.183Z] Start: Run in container: cat /root/.vscode-remote/data/Machine/settings.json
[2021-08-22T17:46:08.185Z] 
[2021-08-22T17:46:08.185Z] cat: /root/.vscode-remote/data/Machine/settings.json: No such file or directory
[2021-08-22T17:46:08.185Z] Exit code 1
[2021-08-22T17:46:08.185Z] Stop (2 ms): Run in container: cat /root/.vscode-remote/data/Machine/settings.json
[2021-08-22T17:46:08.185Z] Stop (3597 ms): Resolving Remote
[2021-08-22T17:46:08.532Z] @microsoft/vscode-dev-containers-cli 0.42.0.
[2021-08-22T17:46:08.532Z] Start: Resolving Remote
[2021-08-22T17:46:08.549Z] Start: Run: docker ps -q -a --filter label=Type=codespaces
[2021-08-22T17:46:08.582Z] Stop (33 ms): Run: docker ps -q -a --filter label=Type=codespaces
[2021-08-22T17:46:08.582Z] Start: Run: docker inspect --type container 8ff6fe1b0582
[2021-08-22T17:46:08.615Z] Stop (33 ms): Run: docker inspect --type container 8ff6fe1b0582
[2021-08-22T17:46:08.616Z] Start: Inspecting container
[2021-08-22T17:46:08.616Z] Start: Run: docker inspect --type container 8ff6fe1b058212f14aed4a8ae9eb9cd60be2cefe41f783396ffea115e84e3853
[2021-08-22T17:46:08.652Z] Stop (36 ms): Run: docker inspect --type container 8ff6fe1b058212f14aed4a8ae9eb9cd60be2cefe41f783396ffea115e84e3853
[2021-08-22T17:46:08.652Z] Stop (36 ms): Inspecting container
[2021-08-22T17:46:08.653Z] Start: Run in container: /bin/sh
[2021-08-22T17:46:08.657Z] Start: Run in container: uname -m
[2021-08-22T17:46:08.748Z] x86_64
[2021-08-22T17:46:08.748Z] 
[2021-08-22T17:46:08.748Z] Stop (91 ms): Run in container: uname -m
[2021-08-22T17:46:08.748Z] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2021-08-22T17:46:08.749Z] NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.5
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
[2021-08-22T17:46:08.749Z] 
[2021-08-22T17:46:08.749Z] Stop (1 ms): Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2021-08-22T17:46:08.750Z] Start: Run in container: cat /etc/passwd
[2021-08-22T17:46:08.751Z] Stop (1 ms): Run in container: cat /etc/passwd
[2021-08-22T17:46:08.752Z] Start: Run in container: test -d /root/.vscode-remote
[2021-08-22T17:46:08.753Z] 
[2021-08-22T17:46:08.753Z] 
[2021-08-22T17:46:08.753Z] Stop (1 ms): Run in container: test -d /root/.vscode-remote
[2021-08-22T17:46:08.753Z] Start: Run in container: test -f /var/vscode-remote/.patchEtcEnvironmentMarker
[2021-08-22T17:46:08.753Z] 
[2021-08-22T17:46:08.753Z] 
[2021-08-22T17:46:08.753Z] Stop (0 ms): Run in container: test -f /var/vscode-remote/.patchEtcEnvironmentMarker
[2021-08-22T17:46:08.754Z] Start: Run in container: test -f /var/vscode-remote/.patchEtcProfileMarker
[2021-08-22T17:46:08.754Z] 
[2021-08-22T17:46:08.754Z] 
[2021-08-22T17:46:08.754Z] Stop (0 ms): Run in container: test -f /var/vscode-remote/.patchEtcProfileMarker
[2021-08-22T17:46:08.755Z] Start: Run in container: test ! -f '/root/.vscode-remote/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.755Z] 
[2021-08-22T17:46:08.755Z] 
[2021-08-22T17:46:08.755Z] Exit code 1
[2021-08-22T17:46:08.755Z] Stop (0 ms): Run in container: test ! -f '/root/.vscode-remote/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.755Z] Start: Run in container: cat /root/.vscode-remote/data/Machine/settings.json
[2021-08-22T17:46:08.757Z] 
[2021-08-22T17:46:08.757Z] cat: /root/.vscode-remote/data/Machine/settings.json: No such file or directory
[2021-08-22T17:46:08.757Z] Exit code 1
[2021-08-22T17:46:08.757Z] Stop (2 ms): Run in container: cat /root/.vscode-remote/data/Machine/settings.json
[2021-08-22T17:46:08.757Z] userEnvProbe: none (default)
[2021-08-22T17:46:08.757Z] Start: Run in container: test ! -f '/root/.vscode-remote/data/Machine/.onCreateCommandMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.onCreateCommandMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.759Z] 
[2021-08-22T17:46:08.759Z] 
[2021-08-22T17:46:08.759Z] Stop (2 ms): Run in container: test ! -f '/root/.vscode-remote/data/Machine/.onCreateCommandMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.onCreateCommandMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.759Z] Start: Run in container: test ! -f '/root/.vscode-remote/data/Machine/.updateContentCommandMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.updateContentCommandMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.760Z] 
[2021-08-22T17:46:08.760Z] 
[2021-08-22T17:46:08.760Z] Stop (1 ms): Run in container: test ! -f '/root/.vscode-remote/data/Machine/.updateContentCommandMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.updateContentCommandMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.760Z] Start: Run in container: test ! -f '/root/.vscode-remote/data/Machine/.postCreateCommandMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.760Z] Stop (228 ms): Resolving Remote
[2021-08-22T17:46:08.762Z] 
[2021-08-22T17:46:08.762Z] 
[2021-08-22T17:46:08.762Z] Stop (2 ms): Run in container: test ! -f '/root/.vscode-remote/data/Machine/.postCreateCommandMarker' && set -o noclobber && mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
[2021-08-22T17:46:08.762Z] Start: Run in container: mkdir -p '/root/.vscode-remote/data/Machine' && [ "$(cat '/root/.vscode-remote/data/Machine/.postStartCommandMarker' 2>/dev/null)" != '2021-08-22T17:46:07.905431196Z' ] && echo '2021-08-22T17:46:07.905431196Z' > '/root/.vscode-remote/data/Machine/.postStartCommandMarker'
[2021-08-22T17:46:08.764Z] 
[2021-08-22T17:46:08.764Z] 
[2021-08-22T17:46:08.764Z] Stop (2 ms): Run in container: mkdir -p '/root/.vscode-remote/data/Machine' && [ "$(cat '/root/.vscode-remote/data/Machine/.postStartCommandMarker' 2>/dev/null)" != '2021-08-22T17:46:07.905431196Z' ] && echo '2021-08-22T17:46:07.905431196Z' > '/root/.vscode-remote/data/Machine/.postStartCommandMarker'
```

This is probably Github's default container, so I try to rebuild the codespace and get the following build errors, consistently:

```
Configuration starting...
2021-08-22T17:55:54: [2021-08-22T17:55:56.051Z] @microsoft/vscode-dev-containers-cli 0.42.0.
[2021-08-22T17:55:56.051Z] Start: Resolving Remote
[2021-08-22T17:55:56.063Z] Start: Run: docker-compose version --short
[2021-08-22T17:55:56.511Z] Stop (448 ms): Run: docker-compose version --short
[2021-08-22T17:55:56.513Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=totalitylmscom --filter label=com.docker.compose.service=laravel.test
[2021-08-22T17:55:56.542Z] Stop (29 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=totalitylmscom --filter label=com.docker.compose.service=laravel.test
[2021-08-22T17:55:56.543Z] Start: Run: docker-compose -f /var/lib/docker/codespacemount/workspace/totalitylms.com/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config
Error: Command failed: docker-compose -f /var/lib/docker/codespacemount/workspace/totalitylms.com/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config
    at T5 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:267:2348)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async xk (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:267:450)
    at async i8 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:247:9938)
    at async $G (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:293:7173)
    at async Kae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:293:26145)
    at async Yae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:293:25739)
[2021-08-22T17:55:57.011Z] Stop (468 ms): Run: docker-compose -f /var/lib/docker/codespacemount/workspace/totalitylms.com/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config
[2021-08-22T17:55:57.011Z] 
[2021-08-22T17:55:57.011Z] build path /var/lib/docker/codespacemount/workspace/totalitylms.com/vendor/laravel/sail/runtimes/8.0 either does not exist, is not accessible, or is not a valid URL.

[2021-08-22T17:55:57.011Z] Exit code 1
Failed to create container.Error: Command failed: docker-compose -f /var/lib/docker/codespacemount/workspace/totalitylms.com/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml configError Code: 1302Container creation failed.
2021-08-22T17:55:57: Creating recovery container.
2021-08-22T17:55:57: 
```

Do you have any suggestions as to how you get your projects to work with this new Sail configuration option?

Thanks again!
~Mike

**Comment by mikebronner** [comment]
Update: I have been able to get the codespace to build by copying over the sail stubs to the devcontainer folder and updating docker-composer.yml accordingly. The problem is that composer is not installed at build time, so that means the sail stubs are unavailable, as seen in the error above.

So I got composer and npm to build, but am unclear as to how to access the website? `localhost` returns `server not available`. Further, when running `vendor/bin/sail up` I get `Docker is not running.` (I would not expect to have to run sail up in this situation, but thought to try it anyway, just in case.)

Any recommendations would be greatly appreciated.

**Comment by videlalvaro** [comment]
Hi Mike, I was away on holidays. I'll try to get back to you this week

**Comment by videlalvaro** [comment]
What environment are you in? Are you running docker desktop?

Which command did you use to start up your project? Or you just updated sail?

**Comment by mikebronner** [comment]
Hi @videlalvaro, thanks for taking the time. :)

- I'm setting up devcontainers from a RemoteSSH environment in VSCode. In case you aren't familiar with RemoteSSH, it lets me use a remote server as my dev machine in VSCode.
- I do not have docker installed, and was not expecting to require docker, as VSCode devcontainers wouldn't require me to have docker either. The whole point it to have all this remote, right? :)
- I updated sail, set up the devcontainer settings, created the devcontainer, then started the project using `php artisan serve`. I would have expected the devcontainer to serve the website automatically.

Thanks again for your feedback. :) Please let me know if I can provide any additional information to help with clarifying this.

**Comment by videlalvaro** [comment]
VS Code devcontainers do require docker https://code.visualstudio.com/docs/remote/containers#_system-requirements

**Comment by mikebronner** [comment]
After installing docker, the same problems still persist. (I was wrong, I have headless docker installed on my dev server after all.)

**Comment by videlalvaro** [comment]
So with docker installed you have the same output you shared above? Do you mind updating just in case it's different?

**Comment by mikebronner** [comment]
Sorry, we're jumping around a bit. I was unclear in my update: I got past the above errors by updating the configuration files. Give me a bit, I'm fairly swamped at the moment. I will try to recap exactly where things stand later this afternoon when I have some time to go through the entire process again in detail. :) I appreciate your patience and help!

**Comment by videlalvaro** [comment]
No worries. If in the process you can create like a sample app that I could run locally to try to replicate your errors, that'd be helpful

**Comment by mikebronner** [comment]
Good idea :) I'll put that together.

**Comment by mikebronner** [comment]
@videlalvaro Sorry for the delay, other things overtook this effort in priority, but I have started investigating this again and was able to set up a repo for you to try: https://github.com/Valmar-Holdings/test-laravel-codespace

Here's the creation log file:
```
Configuration starting...
2021-11-13T19:51:11: [2021-11-13T19:51:27.099Z] @microsoft/vscode-dev-containers-cli 0.51.2.
[2021-11-13T19:51:27.099Z] Start: Resolving Remote
$ docker-compose version --short
[2021-11-13T19:51:27.582Z] Stop (470 ms): Run: docker-compose version --short
$ docker ps -q -a --filter label=com.docker.compose.project=test-laravel-codespace --filter label=com.docker.compose.service=laravel.test
[2021-11-13T19:51:27.618Z] Stop (35 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=test-laravel-codespace --filter label=com.docker.compose.service=laravel.test
$ docker-compose -f /var/lib/docker/codespacemount/workspace/test-laravel-codespace/docker-compose.yml -f /var/lib/docker/codespacemount/workspace/test-laravel-codespace/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config
Error: Command failed: docker-compose -f /var/lib/docker/codespacemount/workspace/test-laravel-codespace/docker-compose.yml -f /var/lib/docker/codespacemount/workspace/test-laravel-codespace/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config
    at Q5 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:308:1463)
    at async K5 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:285:714)
    at async nF (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:282:452)
    at async o7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:308:10974)
    at async r3 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:328:7701)
    at async dae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:328:27236)
    at async fae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:328:26831)
[2021-11-13T19:51:28.096Z] Stop (477 ms): Run: docker-compose -f /var/lib/docker/codespacemount/workspace/test-laravel-codespace/docker-compose.yml -f /var/lib/docker/codespacemount/workspace/test-laravel-codespace/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config
[2021-11-13T19:51:28.097Z] 
[2021-11-13T19:51:28.097Z] .FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/docker/codespacemount/workspace/test-laravel-codespace/docker-compose.yml'
2021-11-13T19:51:28: 
[2021-11-13T19:51:28.097Z] Exit code 1
Failed to create container.Error: Command failed: docker-compose -f /var/lib/docker/codespacemount/workspace/test-laravel-codespace/docker-compose.yml -f /var/lib/docker/codespacemount/workspace/test-laravel-codespace/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml configError Code: 1302Container creation failed.
2021-11-13T19:51:28: Creating recovery container.
2021-11-13T19:51:28: $ docker exec -u root 7ba3e7c507e4 cat /var/run/sshd.pid
2021-11-13T19:51:35: cat: /var/run/sshd.pid: No such file or directory
2021-11-13T19:51:35: docker process exited with exit code 1
2021-11-13T19:51:35: $ docker chmod 777 /.codespaces/agent/bin/Ssh/installSSH.sh
2021-11-13T19:51:35: docker: 'chmod' is not a docker command.
2021-11-13T19:51:35: See 'docker --help'
2021-11-13T19:51:35: docker process exited with exit code 1
2021-11-13T19:51:35: $ docker exec -u root 7ba3e7c507e4 /bin/sh /workspaces/.codespaces/.persistedshare/installSSH.sh true false
2021-11-13T19:51:35: 
2021-11-13T19:51:35: Github Codespaces ssh install script.
2021-11-13T19:51:35: 
2021-11-13T19:51:35: (*) Detected Alpine Linux
2021-11-13T19:51:35: 
2021-11-13T19:51:35: (*) Updating and upgrading...
2021-11-13T19:51:35: fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
2021-11-13T19:51:35: fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
2021-11-13T19:51:35: v3.14.3-7-g7f922147cf [https://dl-cdn.alpinelinux.org/alpine/v3.14/main]
2021-11-13T19:51:35: v3.14.3-6-gcf6fb8ae91 [https://dl-cdn.alpinelinux.org/alpine/v3.14/community]
2021-11-13T19:51:35: OK: 14947 distinct packages available
2021-11-13T19:51:35: (1/5) Upgrading busybox (1.33.1-r3 -> 1.33.1-r6)
2021-11-13T19:51:36: Executing busybox-1.33.1-r6.post-upgrade
2021-11-13T19:51:36: (2/5) Upgrading alpine-keys (2.3-r1 -> 2.4-r0)
2021-11-13T19:51:36: (3/5) Upgrading ssl_client (1.33.1-r3 -> 1.33.1-r6)
2021-11-13T19:51:36: (4/5) Upgrading libblkid (2.37-r0 -> 2.37.2-r0)
2021-11-13T19:51:36: (5/5) Upgrading libmount (2.37-r0 -> 2.37.2-r0)
2021-11-13T19:51:36: Executing busybox-1.33.1-r6.trigger
2021-11-13T19:51:36: OK: 115 MiB in 108 packages
2021-11-13T19:51:36: 
2021-11-13T19:51:36: (*) Installing ssh server.
2021-11-13T19:51:36: fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
2021-11-13T19:51:36: fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
2021-11-13T19:51:36: (1/5) Installing openssh-sftp-server (8.6_p1-r3)
2021-11-13T19:51:36: (2/5) Installing openssh-server-common (8.6_p1-r3)
2021-11-13T19:51:36: (3/5) Installing openssh-server (8.6_p1-r3)
2021-11-13T19:51:36: (4/5) Installing openssh (8.6_p1-r3)
2021-11-13T19:51:36: (5/5) Installing openssh-server-pam (8.6_p1-r3)
2021-11-13T19:51:36: Executing busybox-1.33.1-r6.trigger
2021-11-13T19:51:36: OK: 117 MiB in 113 packages
2021-11-13T19:51:36: 
2021-11-13T19:51:36: (*) Success!
2021-11-13T19:51:36: 
2021-11-13T19:51:36: docker process exited with exit code 0
2021-11-13T19:51:36: $ docker exec -u root 7ba3e7c507e4 usermod -aG ssh root
2021-11-13T19:51:36: usermod: group 'ssh' does not exist
2021-11-13T19:51:36: docker process exited with exit code 6
2021-11-13T19:51:36: 
```

It appears to be having problems running docker-compose, maybe its not finding the files, etc. Any thoughts?

**Comment by nikans** [comment]
Same here

**Comment by ertuerk-faruk-business** [comment]
Just add

"features": {
		"ghcr.io/devcontainers/features/docker-in-docker": "latest"
}

to your DevContainer Configuration


(And rebuild your container)

**Comment by mikebronner** [comment]
I've been able to set up code spaces successfully now, and created a template that others might use as well here: https://github.com/GeneaLabs/laravel-codespaces-app-template
